import {StyleSheet} from 'react-native';
import {color} from '../../utils/colors';
import {normalize} from '../../utils/dimensions';

export const styles = StyleSheet.create({
  image: {
    alignSelf: 'center',
    height: normalize(105),
    width: normalize(105),
    marginTop: normalize(37),
  },
  modal: {margin: 0, flex: 1},
  modalView: {
    backgroundColor: color.white,
    marginTop: 'auto',
    borderTopEndRadius: normalize(32),
    borderTopLeftRadius: normalize(32),
    height: 'auto',
  },
  lowerView: {
    height: normalize(50),
    width: normalize(275),
    alignSelf: 'center',
    marginTop: normalize(18),
  },
  suretyText: {
    textAlign: 'center',
    color: color.black,
    fontSize: normalize(18),
  },
  bottomView: {
    marginLeft: normalize(20),
    marginTop: normalize(39),
  },
  checkImage: {height: normalize(14), width: normalize(14)},
  checkBlockView: {flexDirection: 'row', marginTop: normalize(16)},
  loosingHead: {
    fontSize: normalize(14),
    fontWeight: '600',
  },
  promotionText: {
    marginLeft: normalize(9),
  },
  termsView: {
    height: normalize(45),
    width: normalize(335),
    alignSelf: 'center',
    marginTop: normalize(22),
  },
  termsText: {
    fontSize: normalize(11),
    color: color.black,
  },
  cancelButton: {
    height: normalize(50),
    width: normalize(163),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: color.white,
    borderWidth: normalize(1),
    borderRadius: normalize(6),
  },
  deleteButton: {
    height: normalize(50),
    width: normalize(163),
    borderRadius: normalize(6),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: color.red,
  },
  bottomButtonView: {
    flexDirection: 'row',
    paddingHorizontal: normalize(20),
    backgroundColor: 'white',
    justifyContent: 'space-between',
    marginBottom: normalize(20),
    marginTop: normalize(15),
  },
  cancelText: {color: color.black, fontSize: 12, fontWeight: 'bold'},
  deleteText: {color: color.white, fontSize: 12, fontWeight: 'bold'},
  delModal: {margin: 0},
  delModalView: {
    borderWidth: 1,
    backgroundColor: color.white,
    borderTopEndRadius: normalize(32),
    borderTopLeftRadius: normalize(32),
    height: 'auto',
    width: normalize(375),
    position: 'absolute',
    bottom: normalize(0),
    paddingBottom: 20,
    paddingHorizontal: normalize(20),
  },
  cancelledText: {
    marginTop: 44,
    textAlign: 'center',
    fontSize: normalize(18),
    marginBottom: normalize(33),
    color: color.black,
  },
  middleText: {
    textAlign: 'left',
    alignSelf: 'center',
    marginBottom: normalize(25),
    fontSize: normalize(14),
    color: color.black,
  },
  bottomText: {
    textAlign: 'left',
    alignSelf: 'center',
    marginBottom: normalize(25),
    fontSize: normalize(11),
    color: color.black,
  },
  gradientStyle: {
    height: 50,
    width: 335,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  button: {height: 50, width: 335, justifyContent: 'center'},
  buttonText: {
    alignSelf: 'center',
    color: color.white,
    fontSize: normalize(12),
  },
  countryModalHeader: {
    marginTop: normalize(35),
    marginBottom: normalize(14),
  },
  itemSeprator: {
    height: 2,
    backgroundColor: color.lightGrey,
  },
  searchView: {
    height: normalize(35),
    backgroundColor: color.Whitesmoke,
    width: '98%',
    alignItems: 'center',
    flexDirection: 'row',
    paddingHorizontal: normalize(10),
    borderRadius: normalize(8),
  },
  search: {
    height: normalize(17),
    width: normalize(17),
    marginRight: normalize(6),
  },
  countryCodeModal: {
    height: '65%',
    borderTopEndRadius: 0,
    borderTopLeftRadius: 0,
    paddingLeft: 40,
  },
});
