export default {
  add: require('../assets/images/add.png'),
  user: require('../assets/images/user.jpeg'),
  check: require('../assets/images/check.jpeg'),
  left: require('../assets/images/left.png'),
  search: require('../assets/images/search.png'),
  splash: require('../assets/images/splash.jpg'),
  callIcon: require('../assets/images/call.png'),
  chatIcon: require('../assets/images/chat.png'),
  nextIcon: require('../assets/images/next.png'),
  audioIcon: require('../assets/images/audio.png'),
  videoIcon: require('../assets/images/video.png'),
  sendButton: require('../assets/images/send.png'),
  homeAddIcon: require('../assets/images/plus.png'),
  statusIcon: require('../assets/images/status.png'),
  homeMenuIcon: require('../assets/images/menu.png'),
  warningIcon: require('../assets/images/warning.png'),
  settingIcon: require('../assets/images/setting.png'),
  calenderIcon: require('../assets/images/calendar.png'),
  callActiveIcon: require('../assets/images/callActive.png'),
  chatActiveIcon: require('../assets/images/chatActive.png'),
  homeSearchIcon: require('../assets/images/homeSearch.png'),
  statusActiveIcon: require('../assets/images/statusActive.png'),
  settingActiveIcon: require('../assets/images/settingActive.png'),
};
