export const string = {
  yes: 'YES',
  ios: 'ios',
  otp: 'Otp',
  home: 'Home',
  chat: 'Chat',
  name: 'Name',
  more: 'More',
  save: 'Save',
  copy: 'Copy',
  call: 'Calls',
  about: 'About',
  users: 'Users',
  login: 'Login',
  inbox: 'Inbox',
  pingMe: 'ƤíղɠⱮҽ',
  active: 'active',
  status: 'Status',
  search: 'Search',
  logout: 'Logout',
  cancel: 'Cancel',
  SetUser: 'SetUser',
  android: 'android',
  profile: 'Profile',
  setting: 'Settings',
  continue: 'Continue',
  messages: 'messages',
  chatRoom: 'ChatRoom',
  homeStack: 'HomeStack',
  addFriend: 'AddFriend',
  headerPingMe: 'քɨռɢʍɛ',
  activeNow: 'Active Now',
  enterCode: 'Enter Code',
  blockUser: 'Block User',
  ConfirmOtp: 'ConfirmOtp',
  loginStack: 'LoginStack',
  homeChatRoom: 'chatroom',
  selectCode: 'select Code',
  contactList: 'ℭ𝔬𝔫𝔱𝔞𝔠𝔱 𝔏𝔦𝔰𝔱',
  // selectCode: 'Select code',
  deleteMe: 'Delete for me',
  smallChatRoom: 'chatroom',
  resendCode: 'Resend Code',
  invalidOtp: 'Invalid Otp',
  userProfile: 'userProfile',
  yourProfile: 'Your Profile',
  phoneNumber: 'Phone Number',
  invalidName: 'Invalid name',
  clearChat: 'Clear all Chat',
  gender: 'Gender (Optional)',
  typingStatus: 'typingStatus',
  splashScreen: 'SplashScreen',
  recommend: 'Recommended both',
  userName: 'UserName (Required)',
  DOB: 'Date Of Birth (Optional)',
  lastName: 'Last Name (Optional)',
  firstName: 'First Name (Required)',
  hardWareBack: 'hardwareBackPress',
  requestExceed: 'Too many requests',
  invalidUserName: 'Invalid username',
  tooManyCase: 'auth/too-many-requests',
  modalClosed: 'Modal has been closed.',
  deleteEveryOne: 'Delete for everyone',
  enterEmail: 'Enter Your Phone Number',
  profileUpdate: 'Profile Image Updated',
  networkIsuue: "Can't connent to internet",
  invalidPhoneNumber: 'Invalid Phone Number',
  invalidPhoneCase: 'auth/invalid-phone-number',
  networkIsuueCase: 'auth/network-request-failed',
  invalidOtpCase: 'auth/invalid-verification-code',
  incorrectName: 'Name should be in correct format',
  sentOtpTo: 'We have sent you an SMS with the code to ',
  incorrectUserName: 'UserName should be in correct format',
  closeApplication: 'You sure you want to close the application?',
  confirmCountryCode:
    'Please confirm your country code and enter your phone number',
};
