export const string = {
  chat: 'Chat',
  call: 'Calls',
  status: 'Status',
  enterCode: 'Enter Code',
  selectCode: 'Select code',
  resendCode: 'Resend Code',
  setting: 'Settings',
  recommend: 'Recommended both',
  enterEmail: 'Enter Your Email / Phone Number',
  sentOtpTo: 'We have sent you an SMS with the code to ',
  userName: 'UserName (Required)',
  firstName: 'First Name (Required)',
  lastName: 'Last Name (Optional)',
  DOB: 'Date Of Birth (Optional)',
  gender: 'Gender (Optional)',
  save: 'Save',
  ConfirmOtp: 'ConfirmOtp',
  SetUser: 'SetUser',
  confirmCountryCode:
    'Please confirm your country code and enter your phone number/email',
};
