export const string = {
  chat: 'Chat',
  save: 'Save',
  call: 'Calls',
  status: 'Status',
  SetUser: 'SetUser',
  setting: 'Settings',
  enterCode: 'Enter Code',
  ConfirmOtp: 'ConfirmOtp',
  selectCode: 'Select code',
  resendCode: 'Resend Code',
  invalidOtp: 'Invalid Otp',
  gender: 'Gender (Optional)',
  recommend: 'Recommended both',
  userName: 'UserName (Required)',
  DOB: 'Date Of Birth (Optional)',
  lastName: 'Last Name (Optional)',
  firstName: 'First Name (Required)',
  requestExceed: 'Too many requests',
  tooManyCase: 'auth/too-many-requests',
  enterEmail: 'Enter Your Phone Number',
  networkIsuue: "Can't connent to internet",
  invalidPhoneNumber: 'Invalid Phone Number',
  invalidPhoneCase: 'auth/invalid-phone-number',
  networkIsuueCase: 'auth/network-request-failed',
  invalidOtpCase: 'auth/invalid-verification-code',
  incorrectName: 'Name should be in correct format',
  incorrectUserName: 'UserName should be in correct format',
  sentOtpTo: 'We have sent you an SMS with the code to ',
  confirmCountryCode:
    'Please confirm your country code and enter your phone number',
};
